# Generated by Django 4.2.14 on 2024-07-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_sku_sizevariant_sku_delete_colorvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='sku',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
