# Generated by Django 4.2.14 on 2024-07-28 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_color_productimage_productvariant_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='varient_sku',
            field=models.CharField(default=1, max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='SKU must contain only letters, numbers, hyphens, and underscores.', regex='^[a-zA-Z0-9_-]*$')]),
            preserve_default=False,
        ),
    ]
