# Generated by Django 4.2.14 on 2024-07-25 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_rename_coupons_coupon'),
        ('orders', '0002_remove_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon', to='promotions.coupon'),
        ),
    ]
