# Generated by Django 4.2.14 on 2024-07-28 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productimage_options_and_more'),
        ('orders', '0004_alter_order_options_order_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(default='0533b881-f795-4b36-814a-333e3473d70d', on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
            preserve_default=False,
        ),
    ]
